### ISSUE TITLE
black on travis

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#822]
From [Travis](https://travis-ci.org/usnistgov/pfhub/builds/418890910):

```
$ nix-shell --pure --command "black --check _data/*.py"
Traceback (most recent call last):
  File "/nix/store/pwybfx22jq07mz9vrbh0369x3wbb6ipn-python3.6-black-18.6b4/bin/.black-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/s9x1fh363bp15f6f1mvaglbhwbb7h9pk-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/s9x1fh363bp15f6f1mvaglbhwbb7h9pk-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/nix/store/s9x1fh363bp15f6f1mvaglbhwbb7h9pk-python3.6-click-6.7/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
Additional information: on this system no suitable UTF-8
locales were discovered.  This most likely requires resolving
by reconfiguring the locale system.
```

**Comment by wd15** [comment]
Fixed with #823
